#!/usr/bin/env bash
# automation/create_desktop_app.sh
# --------------------------------
# Create a proper macOS .app bundle for PartnerDesk Hub on the user's
# Desktop. Double-clicking it launches the Hub WITHOUT a Terminal
# window flash and shows the right app name in the Dock + Spotlight.
#
# Bundle structure (macOS convention):
#   PartnerDesk Hub.app/
#     Contents/
#       Info.plist            metadata (bundle id, name, version)
#       MacOS/
#         PartnerDeskHub      the bash executable launched on click
#       Resources/            (placeholder — for a future .icns icon)
#
# Safety contract:
#   - Never calls OpenAI.
#   - Never posts anything publicly.
#   - Never modifies the database.
#   - Does NOT start the Hub during creation. Only writes the .app
#     bundle on the Desktop. The user starts the Hub by double-
#     clicking the bundle themselves.
#   - The only filesystem write target is the .app directory on the
#     user's Desktop. The project tree is untouched.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# macOS HFS+/APFS is case-insensitive; `pwd` returns whatever case
# happened to be in the path-lookup chain (often lowercased on this
# user's machine). Walk the path bottom-up via Python's pathlib to
# recover the FILESYSTEM-CANONICAL case for each component — important
# for cosmetic correctness in the launcher's embedded path.
ROOT="$(python3 - <<PY
from pathlib import Path
def canonical(p: Path) -> Path:
    if p.parent == p:
        return p
    parent = canonical(p.parent)
    for entry in parent.iterdir():
        if entry.name.lower() == p.name.lower():
            return entry
    return p
print(canonical(Path("$ROOT").resolve()))
PY
)"

DESKTOP="$HOME/Desktop"
APP_DIR="$DESKTOP/PartnerDesk Hub.app"
CONTENTS="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RESOURCES_DIR="$CONTENTS/Resources"
EXECUTABLE="$MACOS_DIR/PartnerDeskHub"
PLIST="$CONTENTS/Info.plist"

if [[ ! -d "$DESKTOP" ]]; then
    echo "Desktop directory not found at $DESKTOP" >&2
    exit 1
fi

# Build the bundle directory tree (idempotent — mkdir -p is a no-op
# if the dirs already exist).
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"

# Info.plist — minimal but valid. Bundle identifier uses a reverse-
# DNS scheme. LSUIElement=false so the app shows in the Dock when
# running (false is the default; we set it explicitly for clarity).
cat > "$PLIST" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>PartnerDesk Hub</string>
    <key>CFBundleDisplayName</key>
    <string>PartnerDesk Hub</string>
    <key>CFBundleIdentifier</key>
    <string>com.mixedmakershop.partnerdesk.hub</string>
    <key>CFBundleVersion</key>
    <string>6.0</string>
    <key>CFBundleShortVersionString</key>
    <string>6.0</string>
    <key>CFBundleExecutable</key>
    <string>PartnerDeskHub</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# Quoted heredoc ('LAUNCHER_EOF') makes the body LITERAL — no shell
# expansion at write time, no escape hell. The __PARTNERDESK_ROOT__
# placeholder is sed-replaced with the actual ROOT path right after.
# This separates the two concerns cleanly: write the launcher
# template, then patch in the path.
cat > "$EXECUTABLE" <<'LAUNCHER_EOF'
#!/bin/bash
# PartnerDesk Hub launcher (inside .app bundle)
# Generated by automation/create_desktop_app.sh
#
# Direct bash invocation of open_hub.sh — no osascript wrapping (the
# previous nested-quote osascript approach hit escape-hell). Output
# is captured to a log; a native macOS alert appears on failure so
# the user sees a visible error instead of a silent dead browser tab.
# Always exits 0 — non-zero would trigger macOS's generic
# "application unexpectedly quit" dialog on top of our alert.
#
# If macOS sandboxes this .app from reading ~/Documents (TCC Files-
# and-Folders), the log will show "Operation not permitted" and the
# alert will surface it. Resolution: System Settings > Privacy &
# Security > Files and Folders > grant access, OR move the project
# outside ~/Documents.
set -u

ROOT="__PARTNERDESK_ROOT__"
LOG="/tmp/partnerdesk-hub-launch.log"

{
  echo "--- Launch at $(date '+%Y-%m-%d %H:%M:%S') ---"
  cd "$ROOT" || exit 1
  /bin/bash "$ROOT/automation/open_hub.sh"
} > "$LOG" 2>&1

rc=$?

if [[ $rc -ne 0 ]]; then
  TAIL=$(tail -12 "$LOG" 2>/dev/null | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' '\r')
  /usr/bin/osascript -e "display alert \"PartnerDesk Hub failed to start\" message \"Exit code: $rc\r\rLast log lines:\r$TAIL\r\rFull log:\r$LOG\" as critical" >/dev/null 2>&1
fi

exit 0
LAUNCHER_EOF

# Patch the placeholder with the canonical-case ROOT. BSD sed (macOS)
# requires '' after -i for in-place edit. Pipe-delimiter avoids
# escaping any forward-slashes in the path.
sed -i '' "s|__PARTNERDESK_ROOT__|$ROOT|g" "$EXECUTABLE"

chmod +x "$EXECUTABLE"

# Touch the bundle root so Finder/LaunchServices notice the new app
# and refresh its display (without this, Finder may show stale state
# from a previous .app at the same path).
touch "$APP_DIR"

echo "Created: $APP_DIR"
echo "Double-click it on your Desktop, drag it to the Dock, or find it"
echo "with Spotlight (Cmd-Space → 'PartnerDesk Hub')."
