#!/usr/bin/env bash
# automation/create_desktop_launcher.sh
# ------------------------------------
# Create a clickable "PartnerDesk Hub.command" file on the user's
# Desktop. Double-clicking opens Terminal, starts the Hub server if
# needed, and opens the browser.
#
# Safety contract:
#   - Never calls OpenAI.
#   - Never posts anything publicly.
#   - Never modifies the database.
#   - Does NOT start the Hub during creation. Only writes the launcher
#     file. The user starts the Hub by double-clicking the icon
#     themselves.
#   - The only filesystem write target is the .command file on the
#     user's Desktop.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DESKTOP="$HOME/Desktop"
LAUNCHER="$DESKTOP/PartnerDesk Hub.command"

if [[ ! -d "$DESKTOP" ]]; then
    echo "Desktop directory not found at $DESKTOP" >&2
    exit 1
fi

# Unquoted heredoc delimiter on purpose: $ROOT must be interpolated at
# creation time so the launcher embeds the actual absolute repo path.
# A future repo move just means re-running this script.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# PartnerDesk Hub launcher
# Generated by automation/create_desktop_launcher.sh
# Double-click to start the local Hub server and open it in the browser.
cd "$ROOT"
bash automation/open_hub.sh
EOF

chmod +x "$LAUNCHER"

echo "Created: $LAUNCHER"
echo "Double-click it on your Desktop to open the Hub."
