#!/usr/bin/env bash
# automation/create_desktop_app.sh
# --------------------------------
# Create a proper macOS .app bundle for PartnerDesk Hub on the user's
# Desktop. Double-clicking it launches the Hub WITHOUT a Terminal
# window flash and shows the right app name in the Dock + Spotlight.
#
# Bundle structure (macOS convention):
#   PartnerDesk Hub.app/
#     Contents/
#       Info.plist            metadata (bundle id, name, version)
#       MacOS/
#         PartnerDeskHub      the bash executable launched on click
#       Resources/            (placeholder — for a future .icns icon)
#
# Safety contract:
#   - Never calls OpenAI.
#   - Never posts anything publicly.
#   - Never modifies the database.
#   - Does NOT start the Hub during creation. Only writes the .app
#     bundle on the Desktop. The user starts the Hub by double-
#     clicking the bundle themselves.
#   - The only filesystem write target is the .app directory on the
#     user's Desktop. The project tree is untouched.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DESKTOP="$HOME/Desktop"
APP_DIR="$DESKTOP/PartnerDesk Hub.app"
CONTENTS="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RESOURCES_DIR="$CONTENTS/Resources"
EXECUTABLE="$MACOS_DIR/PartnerDeskHub"
PLIST="$CONTENTS/Info.plist"

if [[ ! -d "$DESKTOP" ]]; then
    echo "Desktop directory not found at $DESKTOP" >&2
    exit 1
fi

# Build the bundle directory tree (idempotent — mkdir -p is a no-op
# if the dirs already exist).
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"

# Info.plist — minimal but valid. Bundle identifier uses a reverse-
# DNS scheme. LSUIElement=false so the app shows in the Dock when
# running (false is the default; we set it explicitly for clarity).
cat > "$PLIST" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>PartnerDesk Hub</string>
    <key>CFBundleDisplayName</key>
    <string>PartnerDesk Hub</string>
    <key>CFBundleIdentifier</key>
    <string>com.mixedmakershop.partnerdesk.hub</string>
    <key>CFBundleVersion</key>
    <string>6.0</string>
    <key>CFBundleShortVersionString</key>
    <string>6.0</string>
    <key>CFBundleExecutable</key>
    <string>PartnerDeskHub</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# Unquoted heredoc on the executable: $ROOT must be interpolated at
# creation time so the launcher embeds the actual repo path. Future
# repo move just means re-running this script.
cat > "$EXECUTABLE" <<EOF
#!/usr/bin/env bash
# PartnerDesk Hub launcher (inside .app bundle)
# Generated by automation/create_desktop_app.sh
# Defer to open_hub.sh — that script handles probing, starting uvicorn,
# and opening the browser. We ALWAYS exit 0 because a non-zero exit
# triggers macOS's generic "application unexpectedly quit" dialog.
cd "$ROOT"
bash automation/open_hub.sh || true
EOF

chmod +x "$EXECUTABLE"

# Touch the bundle root so Finder/LaunchServices notice the new app
# and refresh its display (without this, Finder may show stale state
# from a previous .app at the same path).
touch "$APP_DIR"

echo "Created: $APP_DIR"
echo "Double-click it on your Desktop, drag it to the Dock, or find it"
echo "with Spotlight (Cmd-Space → 'PartnerDesk Hub')."
