"""
daily_report.py
---------------
Generates a per-day activity report file at reports/YYYY-MM-DD.md.

Called by daily_ops.py (the cron) each morning with --yesterday so the
prior 24 hours' activity gets captured in full once the day is over.

Safety contract:
- Read-only against the SQLite DB (no UPDATE / INSERT / DELETE).
- The only filesystem write target is reports/*.md.
- No outbound network calls.
- No secrets in report content — only counts, topic labels, platform
  labels, and timestamps.
- Idempotent: re-running for a date overwrites that date's report
  with refreshed counts. Other dates are untouched.

CLI:
    python3 automation/daily_report.py                   # today's report
    python3 automation/daily_report.py --yesterday        # yesterday's
    python3 automation/daily_report.py 2026-05-28        # specific date
    python3 automation/daily_report.py --backfill 14     # last 14 days,
                                                          # skipping
                                                          # existing files
"""

from datetime import datetime, timedelta, date
from pathlib import Path
import sqlite3
import sys


ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "database" / "partnerdesk.db"
REPORTS_DIR = ROOT / "reports"


def _query_counts(conn: sqlite3.Connection, date_str: str) -> dict:
    """Read-only aggregation for the given YYYY-MM-DD date."""
    out = {
        "drafts_generated": conn.execute(
            "SELECT COUNT(*) FROM posts WHERE date(created_at) = ?",
            (date_str,),
        ).fetchone()[0],
        "approvals": conn.execute(
            "SELECT COUNT(*) FROM post_history WHERE date(posted_date) = ?",
            (date_str,),
        ).fetchone()[0],
        "publishes": conn.execute(
            "SELECT COUNT(*) FROM posts "
            "WHERE status = 'posted' AND date(posted_at) = ?",
            (date_str,),
        ).fetchone()[0],
        "by_topic": conn.execute(
            "SELECT topic, COUNT(*) FROM post_history "
            "WHERE date(posted_date) = ? "
            "GROUP BY topic ORDER BY COUNT(*) DESC, topic ASC",
            (date_str,),
        ).fetchall(),
        "by_platform": conn.execute(
            "SELECT platform, COUNT(*) FROM post_history "
            "WHERE date(posted_date) = ? "
            "GROUP BY platform ORDER BY COUNT(*) DESC, platform ASC",
            (date_str,),
        ).fetchall(),
    }
    return out


def _format_report(date_str: str, counts: dict) -> str:
    lines: list[str] = [
        f"# Daily Report — {date_str}",
        "",
        "## Summary",
        f"- Drafts generated: **{counts['drafts_generated']}**",
        f"- Posts approved:   **{counts['approvals']}**",
        f"- Posts published:  **{counts['publishes']}**",
        "",
    ]
    if counts["by_topic"]:
        lines.append("## Approvals by Topic")
        for topic, n in counts["by_topic"]:
            lines.append(f"- {topic} — {n}")
        lines.append("")
    if counts["by_platform"]:
        lines.append("## Approvals by Platform")
        for platform, n in counts["by_platform"]:
            lines.append(f"- {platform} — {n}")
        lines.append("")
    if not (counts["by_topic"] or counts["by_platform"]):
        lines.append("_No approval activity on this date._")
        lines.append("")
    lines.append("---")
    lines.append(
        f"Generated by daily_report.py at "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    return "\n".join(lines) + "\n"


def write_daily_report(target_date: str | None = None) -> Path:
    """
    Generate and write the report for target_date (defaults to today).
    Returns the absolute path to the written file. Idempotent:
    overwrites if a file exists for that date.
    """
    target_date = target_date or date.today().strftime("%Y-%m-%d")
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / f"{target_date}.md"
    conn = sqlite3.connect(DB_PATH)
    try:
        counts = _query_counts(conn, target_date)
    finally:
        conn.close()
    out_path.write_text(_format_report(target_date, counts), encoding="utf-8")
    return out_path


def _yesterday_str() -> str:
    return (date.today() - timedelta(days=1)).strftime("%Y-%m-%d")


def main(argv: list[str]) -> int:
    if len(argv) > 2 and argv[1] == "--backfill":
        try:
            n = int(argv[2])
        except ValueError:
            print(f"Invalid backfill count: {argv[2]}")
            return 2
        if n < 0 or n > 365:
            print(f"--backfill must be 0..365, got {n}")
            return 2
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        written = 0
        for i in range(n):
            d = (date.today() - timedelta(days=i)).strftime("%Y-%m-%d")
            if (REPORTS_DIR / f"{d}.md").is_file():
                continue
            write_daily_report(d)
            written += 1
        print(f"Backfill complete: {written} new report(s) written.")
        return 0

    if len(argv) > 1 and argv[1] == "--yesterday":
        target = _yesterday_str()
    elif len(argv) > 1:
        target = argv[1]
        # Light validation — strict format check.
        if len(target) != 10 or target[4] != "-" or target[7] != "-":
            print(f"Invalid date {target!r}; expected YYYY-MM-DD")
            return 2
    else:
        target = None  # write_daily_report defaults to today

    out = write_daily_report(target)
    print(f"Wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
